### PR TITLE
Emp03

### PR DESCRIPTION
**Pull request by AdamAudio7Xemp01**
Hi 7X lead, 
please review my Com BB and Com C commits in emp03 branch
TransAm

### CODE REVIEW

**Comment by AdamAudio7X** [comment]
Hi Emp01 TA please do this and then  i will merge code

**Comment by AdamAudio7Xemp01** [comment]
Hi Lead,  I made those changes so sending you this message Comment,  TransAm

**Comment by AdamAudio7X** [comment]
Hey TA,  Looking Excellent.  Go ahead and do the merge on this commit!
Leader

**Comment by AdamAudio7Xemp01** [comment]
Sure thing!

**Pull request merged**
